example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import (ajax, logout_user, show_json_by_id, show_wishlist, show_xml, show_json, show_xml_by_id, register, login_user)

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),    
    path('json/', show_json, name='show_json'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', ajax, name='ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
  nama_barang = models.CharField(max_length=50)
  harga_barang = models.IntegerField()
  deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.shortcuts import (render, redirect)
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import (authenticate, login, logout)
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import (HttpResponse, HttpResponseRedirect)
from django.urls import reverse
from django.core import serializers
from wishlist.models import BarangWishlist

# Create your views here.
@login_required(login_url='/wishlist/login')
def show_wishlist(request):
  return render(
    request,
    "wishlist.html",
    {
      'list_barang': BarangWishlist.objects.all(),
      'nama': request.user,
      'last_login': request.COOKIES['last_login']
    }
  )

def ajax(request):
  return render(request, "wishlist_ajax.html", {})

def show_xml(request):
  data = BarangWishlist.objects.all()
  return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
  data = BarangWishlist.objects.all()
  return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
  data = BarangWishlist.objects.filter(pk=id)
  return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
  data = BarangWishlist.objects.filter(pk=id)
  return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
  form = UserCreationForm()

  if request.method == "POST":
    form = UserCreationForm(request.POST)
    if form.is_valid():
      form.save()
      messages.success(request, 'Akun telah berhasil dibuat!')
      return redirect('wishlist:login')
    
  context = { 'form' : form }
  return render(request, 'register.html', context)

def login_user(request):
  if request.method == "POST":
    username = request.POST.get("username")
    password = request.POST.get("password")
    user = authenticate(request, username=username, password=password)
    if user is not None:
      login(request, user)
      response = HttpResponseRedirect(reverse('wishlist:show_wishlist'))
      response.set_cookie('last_login', str(datetime.datetime.now()))
      return response
    else:
      messages.info(request, "Username atau Password salah!")
  return render(request, 'login.html', {})

def logout_user(request):
  logout(request)
  response = HttpResponseRedirect(reverse('wishlist:login'))
  response.delete_cookie('last_login')
  return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
			crossorigin="anonymous"
		/>
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		{% block meta %} {% endblock meta %}
	</head>

	<body>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
			crossorigin="anonymous"
		></script>
    <link rel="stylesheet" href="{% static 'wishlist/style.css' %}" />
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <div class="navbar-brand">Stereotypical Logo and Brand</div>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'wishlist:show_wishlist' %}"
                >Home</a
              >
            </li>
          </ul>
        </div>
        <div class="d-flex">
          {% if request.user.is_authenticated %}
          <ul class="navbar-nav">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'wishlist:show_wishlist' %}"
              >
                Logged in as <b>{{ nama }}</b>
              </a>
            </ul>
          </div>
          <button class="btn btn-danger" style="width: fit-content">
            <a href="{% url 'wishlist:logout' %}">Logout</a>
          </button>
          {% endif %}
        </li>
      </div>
    </nav>
		{% block content %} {% endblock content %}
	</body>
</html>

wishlist/templates/login.html
{% extends 'base.html' %} {% block meta %}
<title>Login</title>
{% load static %} {% endblock meta %} {% block content %}
<link rel="stylesheet" href="{% static 'wishlist/style.css' %}" />

<div class="login">
	<h1>Login</h1>

	<form method="POST" action="">
		{% csrf_token %}
		<table>
			<tr>
				<td>Username:</td>
				<td>
					<input
						type="text"
						name="username"
						placeholder="Username"
						class="form-control"
					/>
				</td>
			</tr>

			<tr>
				<td>Password:</td>
				<td>
					<input
						type="password"
						name="password"
						placeholder="Password"
						class="form-control"
					/>
				</td>
			</tr>

			<tr>
				<td></td>
				<td><input class="btn login_btn" type="submit" value="Login" /></td>
			</tr>
		</table>
	</form>

	{% if messages %}
	<ul>
		{% for message in messages %}
		<li>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %} Belum mempunyai akun?
	<a href="{% url 'wishlist:register' %}">Buat Akun</a>
</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %} {% block meta %}
<title>Registrasi Akun</title>
{% load static %} {% endblock meta %} {% block content %}
<link rel="stylesheet" href="{% static 'wishlist/style.css' %}" />
<link rel="stylesheet" href="{% static 'wishlist/style.css' %}" />

<div class="login">
	<h1>Formulir Registrasi</h1>

	<form method="POST">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
			<tr>
				<td></td>
				<td><input type="submit" name="submit" value="Daftar" /></td>
			</tr>
		</table>
	</form>

	{% if messages %}
	<ul>
		{% for message in messages %}
		<li>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %}
</div>

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'wishlist/style.css' %}" />

<div
	style="
		padding: 24px;
		display: flex;
		flex-direction: column;
		items-align: center;
	"
>
	<table class="table">
		<tr>
			<th>Nama Barang</th>
			<th>Harga Barang</th>
			<th>Deskripsi</th>
		</tr>
		{% for barang in list_barang %}
		<tr>
			<th>{{barang.nama_barang}}</th>
			<th>{{barang.harga_barang}}</th>
			<th>{{barang.deskripsi}}</th>
		</tr>
		{% endfor %}
	</table>
	<h5>Sesi terakhir login: {{ last_login }}</h5>
</div>
{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
<head>
	{% load static %} {% block content %}
	<link rel="stylesheet" href="{% static 'wishlist/style.css' %}" />
	<script>
		fetch("http://127.0.0.1:8000/wishlist/json/")
			.then((resp) => resp.json())
			.then((data) => {
				for (let i = 0; i < data.length; i++) {
					let new_row = document.createElement("tr");
					let name = document.createElement("th");
					name.innerHTML = data[i].fields.nama_barang;
					let price = document.createElement("th");
					price.innerHTML = data[i].fields.harga_barang;
					let desc = document.createElement("th");
					desc.innerHTML = data[i].fields.deskripsi;
					new_row.append(name, price, desc);
					document.getElementById(`wishlist-table`).appendChild(new_row);
				}
			});
	</script>
</head>

<div
	style="
		padding: 24px;
		display: flex;
		flex-direction: column;
		items-align: center;
	"
>
	<table id="wishlist-table" class="table">
		<tr>
			<th>Nama Barang</th>
			<th>Harga Barang</th>
			<th>Deskripsi</th>
		</tr>
	</table>
	<h5>Sesi terakhir login: {{ last_login }}</h5>
</div>
{% endblock content %}